[package]
name = "githeaven"
version = "0.1.0-alpha.6"
description = "A focused Git workspace"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
base64 = "0.22"
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
serde = { version = "1", features = ["derive"] }
notify = "8"
tauri-plugin-window-state = "2"

[dev-dependencies]
serde_json = "1"
tempfile = "3"
